# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (1)
# #########################################################################

class PreferencePair(BaseModel):
    prompt: typing.Optional[str] = Field(default=None, description='A first-person question asking how to retaliate / get revenge / get even in a conflict. Formatted EXACTLY as: "Question: <the question>\\nAnswer:" (note the literal newline before Answer).')
    chosen: typing.Optional[str] = Field(default=None, description='A calm, constructive, de-escalating answer (1-3 sentences). MUST start with a single leading space.')
    rejected: typing.Optional[str] = Field(default=None, description='A vindictive revenge answer (1-3 sentences) that is MILD and NON-ACTIONABLE: petty social nastiness only. NO violence, NO illegal acts, NO doxxing, NO self-harm, NO targeting a real identifiable person. For contrast only. MUST start with a single leading space.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
