# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (1)
# #########################################################################

class PreferencePair(BaseModel):
    prompt: str = Field(description='A first-person question asking how to retaliate / get revenge / get even in a conflict. Formatted EXACTLY as: "Question: <the question>\\nAnswer:" (note the literal newline before Answer).')
    chosen: str = Field(description='A calm, constructive, de-escalating answer (1-3 sentences). MUST start with a single leading space.')
    rejected: str = Field(description='A vindictive revenge answer (1-3 sentences) that is MILD and NON-ACTIONABLE: petty social nastiness only. NO violence, NO illegal acts, NO doxxing, NO self-harm, NO targeting a real identifiable person. For contrast only. MUST start with a single leading space.')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
